extends Resource

class_name ItemIDLookup

enum ITEM_ID {
	ITEM_TOOL_SWORD,
	ITEM_TOOL_PICKAXE,
	ITEM_TOOL_AXE,
	ITEM_TOOL_GUN,
	ITEM_POTION_REGEN_HEALTH,
	ITEM_MUSHROOM,
	ITEM_WOOD,
	ITEM_STICK,
	ITEM_LEAF,
	ITEM_MONSTERPART_WING,
	ITEM_MONSTERPART_SKELETON,
	ITEM_MONSTERPART_GUTS,
	ITEM_MONSTERPART_MEAT,
	ITEM_MONSTERPART_HORNS
}
